
.PHONY:clean, pi_1, pi_2, pi_3
clean:
	rm -rf pi_1, pi_2, pi_3

pi_1:
	gcc -o pi_1 pi_1.c -lpthread \
	&& ./pi_1

pi_2:
	gcc -o pi_2 pi_2.c -lpthread \
	&& ./pi_2	

pi_3:
	gcc -o pi_3 pi_3.c -lpthread \	
	&& ./pi_3